"""fixer_exchange

Revision ID: 20190321212933
Revises: 20190314182214
Create Date: 2019-03-21 21:29:33.972277

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm.session import Session

from app.exchanges import FixerExchange

# revision identifiers, used by Alembic.
revision = "20190321212933"
down_revision = "20190314182214"
branch_labels = None
depends_on = None

Base = declarative_base()


class Exchange(Base):
    __tablename__ = "exchanges"

    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.Text, nullable=False, index=True)
    weight = sa.Column(sa.Integer, nullable=False)
    is_active = sa.Column(sa.Boolean, nullable=False)


def upgrade():
    session = Session(bind=op.get_bind())
    session.add(Exchange(name=FixerExchange.name, is_active=False, weight=10))
    session.flush()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
