"""add_vipchanger_exchange

Revision ID: 20190404023229
Revises: 20190402045327
Create Date: 2019-04-04 02:32:29.389640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from sqlalchemy.ext.declarative import declarative_base

from app.exchanges import VipChangerExchange

# revision identifiers, used by Alembic.
revision = '20190404023229'
down_revision = '20190402045327'
branch_labels = None
depends_on = None

Base = declarative_base()


class Exchange(Base):
    __tablename__ = 'exchanges'

    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.Text, nullable=False, index=True)
    weight = sa.Column(sa.Integer, nullable=False)
    is_active = sa.Column(sa.Boolean, nullable=False)


def upgrade():
    session = Session(bind=op.get_bind())
    session.add(Exchange(name=VipChangerExchange.name, is_active=True, weight=30))
    session.flush()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
