"""requests_log_refact

Revision ID: 20190314103043
Revises: 20190311151631
Create Date: 2019-03-14 10:30:43.853502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import func, and_
from sqlalchemy.orm.session import Session
from sqlalchemy.ext.declarative import declarative_base

# revision identifiers, used by Alembic.
revision = '20190314103043'
down_revision = '20190311151631'
branch_labels = None
depends_on = None

MAX_LEN_MSG_REQUESTS_LOG = 100

Base = declarative_base()


class RequestsLog(Base):
    __tablename__ = 'requests_log'

    id = sa.Column(sa.Integer, primary_key=True)
    message = sa.Column(sa.Text, nullable=False)
    tag = sa.Column(sa.Text, nullable=False)


def upgrade():
    session = Session(bind=op.get_bind())
    session.query(RequestsLog).filter(
        func.length(RequestsLog.message) > MAX_LEN_MSG_REQUESTS_LOG
    ).delete(synchronize_session=False)
    session.query(RequestsLog).filter_by(tag=None).update({'tag': ''})

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests_log', 'tag',
                    existing_type=sa.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests_log', 'tag',
                    existing_type=sa.TEXT(),
                    nullable=True)
    # ### end Alembic commands ###
