"""add_syp_exchange

Revision ID: 20190326131313
Revises: 20190326083625
Create Date: 2019-03-26 13:13:13.581001

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm.session import Session

from app.exchanges import SpTodayExchange

# revision identifiers, used by Alembic.
revision = "20190326131313"
down_revision = "20190326083625"
branch_labels = None
depends_on = None


Base = declarative_base()


class Exchange(Base):
    __tablename__ = "exchanges"

    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.Text, nullable=False, index=True)
    weight = sa.Column(sa.Integer, nullable=False)
    is_active = sa.Column(sa.Boolean, nullable=False)


def upgrade():
    session = Session(bind=op.get_bind())
    session.add(Exchange(name=SpTodayExchange.name, is_active=True, weight=15))
    session.flush()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
