"""events

Revision ID: 20190314175025
Revises: 20190314103043
Create Date: 2019-03-14 17:50:25.703943

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20190314175025'
down_revision = '20190314103043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=False),
                    sa.Column('event', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chat_id', 'event')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
