"""chat_settings

Revision ID: 20190314182214
Revises: 20190314175025
Create Date: 2019-03-14 18:22:14.635279

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from sqlalchemy.ext.declarative import declarative_base

# revision identifiers, used by Alembic.
revision = '20190314182214'
down_revision = '20190314175025'
branch_labels = None
depends_on = None

Base = declarative_base()


class Chat(Base):
    __tablename__ = 'chats'

    id = sa.Column(sa.BigInteger, primary_key=True)
    default_currency = sa.Column(sa.Text, default='USD', nullable=False)
    default_currency_position = sa.Column(sa.Boolean, default=True, nullable=False)
    created_at = sa.Column(sa.TIMESTAMP, server_default=sa.func.now(), nullable=False)
    modified_at = sa.Column(sa.TIMESTAMP, server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('default_currency', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('default_currency_position', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    session = Session(bind=op.get_bind())
    session.query(Chat).update({
        'default_currency': 'USD',
        'default_currency_position': True,
        'modified_at': Chat.modified_at,
    })

    op.alter_column('chats', 'default_currency', nullable=False)
    op.alter_column('chats', 'default_currency_position', nullable=False)


def downgrade():
    pass
