"""referral_bittrex

Revision ID: 20200329134234
Revises: 20200217062024
Create Date: 2020-03-29 13:42:34.129252

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "20200329134234"
down_revision = "20200217062024"
branch_labels = None
depends_on = None


Base = declarative_base()


class Exchange(Base):
    __tablename__ = "exchanges"

    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.Text, nullable=False, index=True)
    weight = sa.Column(sa.Integer, nullable=False)
    is_active = sa.Column(sa.Boolean, nullable=False)


def upgrade():
    session = Session(bind=op.get_bind())
    session.query(Exchange).filter_by(name="Bittrex").update(
        {
            "name": "[bittrex.com](https://bittrex.com/Account/Register?referralCode=YIV-CNI-13Q)"
        }
    )
    session.flush()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
