"""satang_exchanger

Revision ID: 20200217055212
Revises: 20190903073346
Create Date: 2020-02-17 05:52:12.259761

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm.session import Session

from app.exchanges import SatangExchange

# revision identifiers, used by Alembic.
revision = "20200217055212"
down_revision = "20190903073346"
branch_labels = None
depends_on = None

Base = declarative_base()


class Exchange(Base):
    __tablename__ = "exchanges"

    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.Text, nullable=False, index=True)
    weight = sa.Column(sa.Integer, nullable=False)
    is_active = sa.Column(sa.Boolean, nullable=False)


def upgrade():
    session = Session(bind=op.get_bind())
    session.add(Exchange(name=SatangExchange.name, is_active=True, weight=17))
    session.flush()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
